Add insert article below command
lblod/ember-rdfa-editor-article-structure-plugin pull request #13
Opened 2022-10-17 10:04 UTC by lagartoverde

Solves https://binnenland.atlassian.net/browse/GN-3258

2022-10-21 11:56 UTC, abeforgit requested changes

2022-10-21 11:56 UTC, abeforgit commented on addon/commands/insert-article-below-command.js
> +  removeZeroWidthSpace(text) {
this function is never used

2022-10-21 11:56 UTC, abeforgit commented on addon/components/article-structure-card.hbs
> +    @disabled={{this.isOutsideArticle}}
the button is never enabled

2022-11-03 10:45 UTC, elpoelma approved these changes
Looks good and works as expected an intuitively :smiley:

2022-11-04 11:44 UTC, merged